In [1]:
import pandas as pd

df = pd.read_excel("../plan_de_compras_2025.xlsx")

print("Archivo cargado correctamente")
print("Cantidad de filas y columnas:", df.shape)

Archivo cargado correctamente
Cantidad de filas y columnas: (831, 26)

In [2]:
df.head()

,Unidad de Compra,ID Proyecto,Tipo Proyecto,Estado Proyecto,Código presupuestario,Nombre Proyecto,Descripción Proyecto,Cantidad de Ítems,Nombre ítem,Tipo compra,...,Cargo responsable,Teléfono responsable,Correo responsable,Fecha de Inicio Compra,Fecha Publicación PAC 2025,Cantidad OC Asociadas Ítem 2025,OC Asociada Item 2025,Item De Arraste,Monto De Arrastre,Meses envio OC de Arraste
0,Ministerio de Vivienda y Urbanismo(766),587-259-PC22,Proyecto estratégico,Publicado,2207-2209-33,Servicio arriendo de una plataforma de gestión...,Servicio de arriendo de una plataforma de gest...,2,Servicio arriendo de una plataforma de gestión...,1,...,Coordinadora de Tecnologías Informáticas | Sis...,2 -2901 1198-,mzunigas@minvu.cl,2022-11-01,2022-11-08,0,NaN,1,20000000,2025-01-01
1,SEREMI MINVU V REGION,632-28-PC22,Proyecto operacional,Publicado,2206-2206001,Servicio de Mantención y Reparaciones Menores ...,Convenio de Suministro para el Servicio de Man...,1,Mantenimiento y Reparación de Edificaciones,1,...,Encargado Sección Administración y Finanzas,32-2186802-,agardaix@minvu.cl,2022-02-01,2022-11-08,1,632-7-SE22,1,4500000,2025-01-01
2,SEREMI MINVU V REGION,632-32-PC22,Proyecto operacional,Publicado,2204001,Servicios de Impresión-Seremi Valparaiso,Servicios de Impresión de Materiales SEREMI y ...,1,Materiales de Oficina,1,...,Encargado Sección Administración y Finanzas,32-2186802-,agardaix@minvu.cl,2022-08-01,2022-11-08,0,NaN,1,3825000,2025-01-01
3,SEREMI MINVU V REGION,632-34-PC22,Proyecto operacional,Publicado,2209006,Servicio de Arriendo de Impresoras Multifuncio...,Servicio de Arriendo de Impresoras Multifuncio...,2,Arriendo de Equipos Informáticos,1,...,Encargado Sección Administración y Finanzas,32-2186802-,agardaix@minvu.cl,2022-08-01,2022-11-08,1,632-13-CC23,1,4500000,2025-01-01
4,SEREMI MINVU V REGION,632-41-PC22,Proyecto operacional,Publicado,2205005,Servicio de Telefonía Fija-Seremi Valparaiso,Servicio de Telefonía Fija SEREMI,2,Telefonía Fija,1,...,Encargado Sección Administración y Finanzas,322186802,agardaix@minvu.cl,2022-12-01,2022-11-08,0,NaN,1,26400000,2025-01-01

In [10]:
df.columns.tolist()

['Unidad de Compra',
 'ID Proyecto',
 'Tipo Proyecto',
 'Estado Proyecto',
 'Código presupuestario',
 'Nombre Proyecto',
 'Descripción Proyecto',
 'Cantidad de Ítems',
 'Nombre ítem',
 'Tipo compra',
 'Cantidad Productos',
 'Monto Unitario Ítem',
 'Monto Total Ítem Año 2025',
 'Cantidad OC',
 'Meses envío OC',
 'Nombre responsable',
 'Cargo responsable',
 'Teléfono responsable',
 'Correo responsable',
 'Fecha de Inicio Compra',
 'Fecha Publicación PAC 2025',
 'Cantidad OC Asociadas Ítem 2025',
 'OC Asociada Item 2025',
 'Item De Arraste',
 'Monto De Arrastre',
 'Meses envio OC de Arraste']

In [4]:
df.columns.tolist()

['Unidad de Compra',
 'ID Proyecto',
 'Tipo Proyecto',
 'Estado Proyecto',
 'Código presupuestario',
 'Nombre Proyecto',
 'Descripción Proyecto',
 'Cantidad de Ítems',
 'Nombre ítem',
 'Tipo compra',
 'Cantidad Productos',
 'Monto Unitario Ítem',
 'Monto Total Ítem Año 2025',
 'Cantidad OC',
 'Meses envío OC',
 'Nombre responsable',
 'Cargo responsable',
 'Teléfono responsable',
 'Correo responsable',
 'Fecha de Inicio Compra',
 'Fecha Publicación PAC 2025',
 'Cantidad OC Asociadas Ítem 2025',
 'OC Asociada Item 2025',
 'Item De Arraste',
 'Monto De Arrastre',
 'Meses envio OC de Arraste']

In [11]:
df.dtypes

Unidad de Compra                              str
ID Proyecto                                   str
Tipo Proyecto                                 str
Estado Proyecto                               str
Código presupuestario                      object
Nombre Proyecto                               str
Descripción Proyecto                          str
Cantidad de Ítems                           int64
Nombre ítem                                   str
Tipo compra                                 int64
Cantidad Productos                          int64
Monto Unitario Ítem                         int64
Monto Total Ítem Año 2025                   int64
Cantidad OC                                 int64
Meses envío OC                             object
Nombre responsable                            str
Cargo responsable                             str
Teléfono responsable                       object
Correo responsable                            str
Fecha de Inicio Compra             datetime64[us]
Fecha Publicación PAC 2025         datetime64[us]
Cantidad OC Asociadas Ítem 2025             int64
OC Asociada Item 2025                         str
Item De Arraste                             int64
Monto De Arrastre                           int64
Meses envio OC de Arraste          datetime64[us]
dtype: object

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 831 entries, 0 to 830
Data columns (total 26 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Unidad de Compra                 831 non-null    str
 1   ID Proyecto                      831 non-null    str
 2   Tipo Proyecto                    831 non-null    str
 3   Estado Proyecto                  831 non-null    str
 4   Código presupuestario            830 non-null    object
 5   Nombre Proyecto                  831 non-null    str
 6   Descripción Proyecto             831 non-null    str
 7   Cantidad de Ítems                831 non-null    int64
 8   Nombre ítem                      831 non-null    str
 9   Tipo compra                      831 non-null    int64
 10  Cantidad Productos               831 non-null    int64
 11  Monto Unitario Ítem              831 non-null    int64
 12  Monto Total Ítem Año 2025        831 non-null    int64
 13  Cantidad OC                      831 non-null    int64
 14  Meses envío OC                   831 non-null    object
 15  Nombre responsable               831 non-null    str
 16  Cargo responsable                831 non-null    str
 17  Teléfono responsable             831 non-null    object
 18  Correo responsable               831 non-null    str
 19  Fecha de Inicio Compra           831 non-null    datetime64[us]
 20  Fecha Publicación PAC 2025       831 non-null    datetime64[us]
 21  Cantidad OC Asociadas Ítem 2025  831 non-null    int64
 22  OC Asociada Item 2025            708 non-null    str
 23  Item De Arraste                  831 non-null    int64
 24  Monto De Arrastre                831 non-null    int64
 25  Meses envio OC de Arraste        183 non-null    datetime64[us]
dtypes: datetime64[us](3), int64(9), object(3), str(11)
memory usage: 490.4+ KB

In [13]:
df.isnull().sum()

Unidad de Compra                     0
ID Proyecto                          0
Tipo Proyecto                        0
Estado Proyecto                      0
Código presupuestario                1
Nombre Proyecto                      0
Descripción Proyecto                 0
Cantidad de Ítems                    0
Nombre ítem                          0
Tipo compra                          0
Cantidad Productos                   0
Monto Unitario Ítem                  0
Monto Total Ítem Año 2025            0
Cantidad OC                          0
Meses envío OC                       0
Nombre responsable                   0
Cargo responsable                    0
Teléfono responsable                 0
Correo responsable                   0
Fecha de Inicio Compra               0
Fecha Publicación PAC 2025           0
Cantidad OC Asociadas Ítem 2025      0
OC Asociada Item 2025              123
Item De Arraste                      0
Monto De Arrastre                    0
Meses envio OC de Arraste          648
dtype: int64

In [14]:
df.duplicated().sum()

np.int64(0)

In [15]:
df.dtypes

Unidad de Compra                              str
ID Proyecto                                   str
Tipo Proyecto                                 str
Estado Proyecto                               str
Código presupuestario                      object
Nombre Proyecto                               str
Descripción Proyecto                          str
Cantidad de Ítems                           int64
Nombre ítem                                   str
Tipo compra                                 int64
Cantidad Productos                          int64
Monto Unitario Ítem                         int64
Monto Total Ítem Año 2025                   int64
Cantidad OC                                 int64
Meses envío OC                             object
Nombre responsable                            str
Cargo responsable                             str
Teléfono responsable                       object
Correo responsable                            str
Fecha de Inicio Compra             datetime64[us]
Fecha Publicación PAC 2025         datetime64[us]
Cantidad OC Asociadas Ítem 2025             int64
OC Asociada Item 2025                         str
Item De Arraste                             int64
Monto De Arrastre                           int64
Meses envio OC de Arraste          datetime64[us]
dtype: object

In [16]:
df.isnull().sum()

Unidad de Compra                     0
ID Proyecto                          0
Tipo Proyecto                        0
Estado Proyecto                      0
Código presupuestario                1
Nombre Proyecto                      0
Descripción Proyecto                 0
Cantidad de Ítems                    0
Nombre ítem                          0
Tipo compra                          0
Cantidad Productos                   0
Monto Unitario Ítem                  0
Monto Total Ítem Año 2025            0
Cantidad OC                          0
Meses envío OC                       0
Nombre responsable                   0
Cargo responsable                    0
Teléfono responsable                 0
Correo responsable                   0
Fecha de Inicio Compra               0
Fecha Publicación PAC 2025           0
Cantidad OC Asociadas Ítem 2025      0
OC Asociada Item 2025              123
Item De Arraste                      0
Monto De Arrastre                    0
Meses envio OC de Arraste          648
dtype: int64

In [17]:
df.duplicated().sum()

np.int64(0)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 831 entries, 0 to 830
Data columns (total 26 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Unidad de Compra                 831 non-null    str
 1   ID Proyecto                      831 non-null    str
 2   Tipo Proyecto                    831 non-null    str
 3   Estado Proyecto                  831 non-null    str
 4   Código presupuestario            830 non-null    object
 5   Nombre Proyecto                  831 non-null    str
 6   Descripción Proyecto             831 non-null    str
 7   Cantidad de Ítems                831 non-null    int64
 8   Nombre ítem                      831 non-null    str
 9   Tipo compra                      831 non-null    int64
 10  Cantidad Productos               831 non-null    int64
 11  Monto Unitario Ítem              831 non-null    int64
 12  Monto Total Ítem Año 2025        831 non-null    int64
 13  Cantidad OC                      831 non-null    int64
 14  Meses envío OC                   831 non-null    object
 15  Nombre responsable               831 non-null    str
 16  Cargo responsable                831 non-null    str
 17  Teléfono responsable             831 non-null    object
 18  Correo responsable               831 non-null    str
 19  Fecha de Inicio Compra           831 non-null    datetime64[us]
 20  Fecha Publicación PAC 2025       831 non-null    datetime64[us]
 21  Cantidad OC Asociadas Ítem 2025  831 non-null    int64
 22  OC Asociada Item 2025            708 non-null    str
 23  Item De Arraste                  831 non-null    int64
 24  Monto De Arrastre                831 non-null    int64
 25  Meses envio OC de Arraste        183 non-null    datetime64[us]
dtypes: datetime64[us](3), int64(9), object(3), str(11)
memory usage: 490.4+ KB

In [7]:
df.isnull().sum()

Unidad de Compra                     0
ID Proyecto                          0
Tipo Proyecto                        0
Estado Proyecto                      0
Código presupuestario                1
Nombre Proyecto                      0
Descripción Proyecto                 0
Cantidad de Ítems                    0
Nombre ítem                          0
Tipo compra                          0
Cantidad Productos                   0
Monto Unitario Ítem                  0
Monto Total Ítem Año 2025            0
Cantidad OC                          0
Meses envío OC                       0
Nombre responsable                   0
Cargo responsable                    0
Teléfono responsable                 0
Correo responsable                   0
Fecha de Inicio Compra               0
Fecha Publicación PAC 2025           0
Cantidad OC Asociadas Ítem 2025      0
OC Asociada Item 2025              123
Item De Arraste                      0
Monto De Arrastre                    0
Meses envio OC de Arraste          648
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [18]:
nulos = df.isnull().sum()

resumen_nulos = pd.DataFrame({
    "Columna": nulos.index,
    "Valores Nulos": nulos.values
})

resumen_nulos = resumen_nulos[resumen_nulos["Valores Nulos"] > 0]

resumen_nulos

                      Columna  Valores Nulos
4       Código presupuestario              1
22      OC Asociada Item 2025            123
25  Meses envio OC de Arraste            648

In [19]:
df.describe()

,Cantidad de Ítems,Tipo compra,Cantidad Productos,Monto Unitario Ítem,Monto Total Ítem Año 2025,Cantidad OC,Fecha de Inicio Compra,Fecha Publicación PAC 2025,Cantidad OC Asociadas Ítem 2025,Item De Arraste,Monto De Arrastre,Meses envio OC de Arraste
count,831.000000,831.000000,831.0,8.310000e+02,8.310000e+02,831.000000,831,831,831.000000,831.000000,8.310000e+02,183
mean,1.199759,4.657040,1.0,1.085214e+08,1.014853e+08,1.344164,2024-11-24 15:32:16.462093,2025-07-25 18:37:41.371841,125.756919,0.220217,6.139761e+06,2025-01-28 14:33:26.557377
min,1.000000,1.000000,1.0,9.000000e+04,0.000000e+00,1.000000,2022-02-01 00:00:00,2022-11-08 00:00:00,0.000000,0.000000,0.000000e+00,2025-01-01 00:00:00
25%,1.000000,4.000000,1.0,4.200000e+06,3.000000e+06,1.000000,2025-01-01 00:00:00,2025-11-27 00:00:00,1.000000,0.000000,0.000000e+00,2025-01-01 00:00:00
50%,1.000000,6.000000,1.0,4.000000e+07,3.500000e+07,1.000000,2025-01-01 00:00:00,2025-11-27 00:00:00,4.000000,0.000000,0.000000e+00,2025-01-01 00:00:00
75%,1.000000,6.000000,1.0,2.020000e+08,2.020000e+08,1.000000,2025-04-01 00:00:00,2025-11-27 00:00:00,321.000000,0.000000,0.000000e+00,2025-01-01 00:00:00
max,3.000000,6.000000,1.0,4.839000e+09,4.839000e+09,12.000000,2026-03-01 00:00:00,2025-11-27 00:00:00,321.000000,1.000000,6.747510e+08,2025-12-01 00:00:00
std,0.414845,1.942318,0.0,2.036220e+08,2.024663e+08,1.263753,NaN,NaN,155.041024,0.414642,3.466941e+07,NaN

In [20]:
df["Tipo Proyecto"].value_counts()

Tipo Proyecto
Proyecto operacional    613
Proyecto estratégico    218
Name: count, dtype: int64

In [21]:
df["Estado Proyecto"].value_counts()

Estado Proyecto
Actualizado    648
Publicado      183
Name: count, dtype: int64

In [22]:
df["Tipo compra"].value_counts()

Tipo compra
6    486
1    159
4     83
5     79
3     20
2      4
Name: count, dtype: int64

In [23]:
df["Unidad de Compra"].value_counts().head(10)

Unidad de Compra
Ministerio de Vivienda y Urbanismo(766)    684
SEREMI MINVU V REGION                       30
SEREMI MINVU III REGION                     25
SEREMI MINVU VI REGION                      20
SEREMI IV REGION                            14
SEREMI MINVU REGION ARICA Y PARINACOTA       9
SEREMI MINVU XI REGION                       8
SEREMI MINVU II REGION                       8
SEREMI MINVU I REGION                        7
SEREMI VIII REGION                           6
Name: count, dtype: int64

In [24]:
df["Tipo Proyecto"].value_counts()

Tipo Proyecto
Proyecto operacional    613
Proyecto estratégico    218
Name: count, dtype: int64

In [25]:
df["Estado Proyecto"].value_counts()

Estado Proyecto
Actualizado    648
Publicado      183
Name: count, dtype: int64

In [26]:
df["Tipo compra"].value_counts()

Tipo compra
6    486
1    159
4     83
5     79
3     20
2      4
Name: count, dtype: int64

In [27]:
df["Unidad de Compra"].value_counts().head(10)

Unidad de Compra
Ministerio de Vivienda y Urbanismo(766)    684
SEREMI MINVU V REGION                       30
SEREMI MINVU III REGION                     25
SEREMI MINVU VI REGION                      20
SEREMI IV REGION                            14
SEREMI MINVU REGION ARICA Y PARINACOTA       9
SEREMI MINVU XI REGION                       8
SEREMI MINVU II REGION                       8
SEREMI MINVU I REGION                        7
SEREMI VIII REGION                           6
Name: count, dtype: int64