In [1]:
import pandas as pd

In [2]:
df = pd.read_excel("../plan_de_compras_2025.xlsx")

In [6]:
# Buscar columnas relacionadas con teléfono
[col for col in df.columns if "tel" in col.lower()]

['Teléfono responsable']

In [7]:
display(df["Teléfono responsable"].head(20))

0     2 -2901 1198-
1       32-2186802-
2       32-2186802-
3       32-2186802-
4         322186802
5      02-29011184-
6        22-901727-
7                 0
8                 0
9          22901727
10         22901727
11                0
12                0
13                0
14                0
15                0
16                0
17      22-9011395-
18      22-9011395-
19      22-9011395-
Name: Teléfono responsable, dtype: object

In [8]:
print("Nulos:", df["Teléfono responsable"].isna().sum())
print("Valores únicos:", df["Teléfono responsable"].nunique())

Nulos: 0
Valores únicos: 96

In [ ]:
columna_telefono = "Teléfono responsable"

df["telefono_limpio"] = (
    df[columna_telefono]
    .astype("string")
    .str.replace(r"\D+", "", regex=True)  # deja solo dígitos   
    .replace(["", "0"], pd.NA)
)

display(df[[columna_telefono, "telefono_limpio"]].head(20))
print("Nulos en teléfono limpio:", df["telefono_limpio"].isna().sum())

   Teléfono responsable telefono_limpio
0         2 -2901 1198-       229011198
1           32-2186802-       322186802
2           32-2186802-       322186802
3           32-2186802-       322186802
4             322186802       322186802
5          02-29011184-      0229011184
6            22-901727-        22901727
7                     0            <NA>
8                     0            <NA>
9              22901727        22901727
10             22901727        22901727
11                    0            <NA>
12                    0            <NA>
13                    0            <NA>
14                    0            <NA>
15                    0            <NA>
16                    0            <NA>
17          22-9011395-       229011395
18          22-9011395-       229011395
19          22-9011395-       229011395

Nulos en teléfono limpio: 14

In [11]:
df["largo_telefono"] = df["telefono_limpio"].str.len()

display(
    df["largo_telefono"]
    .value_counts(dropna=False)
    .sort_index()
    .to_frame("cantidad")
)

                cantidad
largo_telefono
7                     17
8                    131
9                    235
10                   354
11                    10
12                     5
13                    64
14                     1
<NA>                  14

In [12]:
filas_antes = len(df)

df = df.dropna(subset=["telefono_limpio"]).copy()

print("Filas eliminadas:", filas_antes - len(df))
print("Nulos restantes en teléfono:", df["telefono_limpio"].isna().sum())

Filas eliminadas: 14
Nulos restantes en teléfono: 0